### PR TITLE
Ruby example update. (with deep test gem)

### PR DESCRIPTION
**Pull request by scottcsims**
This is a summary of changes.
Updated rspec from 1.1.8 to 1.1.12. I accomplished this by adding the new deep test 2.0 gem 

The rake file does not need selenium-client 1.2.7. I removed the dependency by  adding the reporting files it was referencing into the lib/reporting  directory. report_formatter_path = “lib/reporting/selenium_test_report_formatter”

Updated selenium-client from 1.2.7 to 1.2.18. With the change to the rake file, I am now able to use the most recent version of selenium-client in my specs.

I am looking forward to getting these improvements in. I am now the maintainer for the deep test gem. I am looking forward to updating rspec support for those who use ruby and the grid.  

The google images UI has changed since the examples were done.  I updated the tests so that they interact with the new google images UI.

Thanks,
Scott Sims

### CODE REVIEW

**Comment by nirvdrum** [comment]
Hi Scott,

I just got around to looking at this.  Sorry about the long delay.

Can you fill me in on why 187092f and 4eab88d are achieving?  I think one is just replacing the other, but I'm not sure why they were separate commits then.  So, I just want to make sure I understand what's going on there.

I added a comment about a bug in f9fa6e2.

Can you please fix the commit message in 3bb27f8?  I assume you meant "deprecated" files.  Although, I'm a bit confused here, too.  Where are they deprecated from?  I don't see any message indicating they were deprecated.

**Comment by scottcsims** [comment]
I fixed the commit message for 3bb27f8.  Commit 187092f  is adding deep test code in the lib. Commit 4eab88d has two important changes.  One is that the actual spec tests needed to be updated because the web site the tests were running against had changed its interface.  The other change is the removal of the deep test code from the lib directory, and added the use of then new deep test gem.

**Comment by nirvdrum** [comment]
Just so I'm 100% sure, the massive changeset in 35beb7e/4eab88d is not adding the DeepTest library, since that's being loaded via gem, but rather is loading code to make use of that library?  And you're the original author of this code?

**Comment by nirvdrum** [comment]
Also, could you please let me know if you have a CLA on file?  If not, could you please submit one?

http://code.google.com/legal/individual-cla-v1.0.html

**Comment by scottcsims** [comment]
35beb7e/4eab88d added the deep test code and 2afc9a7 removes it.  I created the gem in between.

**Comment by scottcsims** [comment]
Running the CLA by the Home Away legal department.  I already have approval to contribute, but I need formal approval from the legal department. I expect to get approval by the end of the day.  I will follow up.

**Comment by scottcsims** [comment]
I completed my CLA and sent it to your gmail account in PDF format.

**Comment by nirvdrum** [comment]
This one was pretty gnarly to get merged in.  I hope I didn't screw it up.  But, because of however you updated the files, all of the commits were duplicated.  From what I gather you probably should have done the second pull request from a separate branch.

Anyway, please try out my version of master and please verify that everything is in there properly.

**Pull request closed without merging**
